sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t vivekjain/docker-first -f Dockerfile.dev .

script:
  - docker run -e CI=true vivekjain/docker-first npm run test 